Document: ap
Title: Debian ap Manual
Author: <insert document author here>
Abstract: This manual describes what ap is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ap/ap.sgml.gz

Format: postscript
Files: /usr/share/doc/ap/ap.ps.gz

Format: text
Files: /usr/share/doc/ap/ap.text.gz

Format: HTML
Index: /usr/share/doc/ap/html/index.html
Files: /usr/share/doc/ap/html/*.html
